; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf

; Requires using the partitioned memory layout
board_build.partitions = partitions.csv

; --- HARDWARE OVERCLOCKING ---
; Force the CPU to run at the maximum speed of 240MHz
board_build.f_cpu = 240000000L

build_unflags = -std=gnu99    ; Remove the default C99 standard of ESP-IDF/Arduino
build_flags = 
    -std=gnu17                ; Use the C17 standard (GNU extension)

; --- SERIAL MONITOR & UPLOAD CONFIGURATION ---
monitor_speed = 115200        ; Log reading speed (ESP32 default should be 115200)
upload_speed = 921600         ; Code upload speed (ESP32 can upload fast at 921600)

monitor_filters = 
    direct                    ; Read colorful logs for a nicer display